name: 'Mirror Repo'
description: 'Mirror repository content with another account/repository'
author: 'PiJa AB'

# Define your inputs here.
inputs:
  PRIVATE_SSH_KEY:
    description: 'Your private ssh key'
    required: true
    default: ''
  REMOTE_REPOSITORY:
    description: 'Repository to sync your content to (organisation/repository)'
    required: true
    default: ''
  REMOTE_BRANCH:
    description: 'Remote branch to overwrite your content to'
    required: true
    default: 'live'

runs:
  using: node20
  main: dist/index.js
